[build]
  command = "npm run build"
  publish = "Site/dist"

[build.environment]
  NODE_VERSION = "18"

# Redirect all URLs to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 