    [build]
      command = "npm install && npm run build"
      publish = "Site/dist"

    [build.environment]
      NODE_VERSION = "18"

    [[redirects]]
      from = "/*"
      to = "/index.html"
      status = 200